name: manager
description: "Vending Machine Manager App"
publish_to: 'none'
version: 0.4.0+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  http_server: ^1.0.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  mobile_scanner: ^7.1.4
  network_info_plus: ^7.0.0
  path: ^1.9.1
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2

    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - images/
