name: kiosk
description: "Vending Machine Kiosk App"
publish_to: 'none'
version: 0.3.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  intl: ^0.20.2
  mobile_scanner: ^7.1.4
  network_info_plus: ^7.0.0
  path: ^1.9.1
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  qr_flutter: ^4.1.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  sqflite: ^2.4.2
  uuid: ^4.5.2
  wakelock_plus: ^1.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.3.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
